FROM node:20-alpine

WORKDIR /app

RUN corepack enable pnpm

COPY package.json pnpm-lock.yaml* ./

RUN pnpm install

COPY . .

EXPOSE 4000

CMD ["sh", "-c", "npx prisma generate && pnpm run start:dev"]
